baseURL = "https://coolgood88142.github.io/"
#title = "我的部落格"
theme = "hamburg"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true

[languages]
	[languages.zh-tw]
        languageCode = "zh-tw"
        languageName = "中文"
        title = "我的部落格"
		contentDir = "content/zh-tw"
		
	[languages.en]
        languageCode = "en"
        languageName = "English"
        title = "My Hugo Blog"
		contentDir = "content/en"
	
[menu]
	[[languages.zh-tw.menu.main]]
		name = "首頁"
		identifier = "home"
		url = "/"

	[[languages.zh-tw.menu.main]]
		name = "標籤"
		identifier = "tags"
		url = "/zh-tw/tags/"
	
	[[languages.zh-tw.menu.main]]
		name = "分類"
		identifier = "categories"
		url = "/zh-tw/categories/"
			
	[[languages.zh-tw.menu.main]]
		name = "關於"
		identifier = "about"
		url = "/zh-tw/pages/about/"
		
	[[languages.en.menu.main]]
		name = "Home"
		identifier = "home"
		url = "/en"

	[[languages.en.menu.main]]
		name = "Tags"
		identifier = "tags"
		url = "/en/tags/"
	
	[[languages.en.menu.main]]
		name = "Categories"
		identifier = "categories"
		url = "/en/categories/"
				
	[[languages.en.menu.main]]
		name = "About"
		identifier = "about"
		url = "/en/pages/about/"
		
[params]
	disqus = "Kai88142"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
	