baseURL = "https://coolgood88142.github.io/"
#title = "我的部落格"
theme = "hamburg"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true

[languages]
	[languages.zh-tw]
        languageCode = "zh-tw"
        languageName = "中文"
        title = "我的部落格"
		contentDir = "content/zh-tw"
		
	[languages.en]
        languageCode = "en"
        languageName = "English"
        title = "My Hugo Blog"
		contentDir = "content/en"
		
		[[languages.en.menu.main]]
			name = "Home"
			identifier = "home"
		
		[[languages.en.menu.main]]
			name = "Tags"
			identifier = "tags"
			
		[[languages.en.menu.main]]
			name = "Categories"
			identifier = "categories"
			
		[[languages.en.menu.main]]
			name = "About"
			identifier = "about"
[menu]
	[[menu.main]]
		name = "首頁"
		identifier = "home"
		url = "/"

	[[menu.main]]
		name = "標籤"
		identifier = "tags"
		url = "tags/"
	
	[[menu.main]]
		name = "分類"
		identifier = "categories"
		url = "categories/"
			
	[[menu.main]]
		name = "關於"
		identifier = "about"
		url = "pages/about/"
		
[params]
	disqus = "Kai88142"

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"
 
[image]
	resampleFilter = "box"
	quality = 75
	