baseURL = "https://coolgood88142.github.io/"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = "true"
#title = "我的部落格"
theme = "hamburg"
copyright = "&copy; Lorem ipsum ... and so on ..."

[menu]
	[[menu.main]]
		name = "About"
		identifier = "about"
		url = "pages/about"

[params]
	subtitle = "我的部落格"
	disqus = "Kai88142"
	
[languages]
	[languages.zh-tw]
			languageCode = "zh-tw"
			languageName = "Chinese(Taiwan)"
			subtitle = "關於我們"