baseURL = "https://coolgood88142.github.io/"
#title = "我的部落格"
theme = "hamburg"
copyright = "&copy; Lorem ipsum ... and so on ..."

[menu]
	[[menu.main]]
		name = "About"
		identifier = "about"
		url = "pages/about"

[params]
	subtitle = "我的部落格"
	disqus = "Kai88142"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
	