baseURL = "https://coolgood88142.github.io/"
#title = "我的部落格"
theme = "hamburg"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true

[languages]
	[languages.zh-tw]
        languageCode = "zh-tw"
        languageName = "中文"
        title = "我的部落格"
		contentDir = "content/zh-tw"
		
	[languages.en]
        languageCode = "en"
        languageName = "English"
        title = "My Hugo Blog"
		contentDir = "content/en"
	
[menu]
	[[menu.main]]
		name = "Home"
		identifier = "home"
		url = "/"

	[[menu.main]]
		name = "Tags"
		identifier = "tags"
		url = "tags/"
	
	[[menu.main]]
		name = "Categories"
		identifier = "categories"
		url = "categories/"
			
	[[menu.main]]
		name = "About"
		identifier = "about"
		url = "pages/about/"
		
[params]
	disqus = "Kai88142"

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"
 
[image]
	resampleFilter = "box"
	quality = 75
	